### ISSUE TITLE
Taobao Login

### ISSUE THREAD

**Issue by MihaiWill** [wkunzhi/Python3-Spider#16]
Hi, 
I used this script without problems a few months ago, but now, sometimes, I get this error:
```
Traceback (most recent call last):
  File "taobaoLogin.py", line 135, in <module>
    loop.run_until_complete(task)
  File "C:\Users\mihai\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "taobaoLogin.py", line 100, in main
    await self.page.click('div.login-switch')
  File "C:\Users\mihai\Anaconda3\lib\site-packages\pyppeteer\page.py", line 1507, in click
    await frame.click(selector, options, **kwargs)
  File "C:\Users\mihai\Anaconda3\lib\site-packages\pyppeteer\frame_manager.py", line 569, in click
    raise PageError('No node found for selector: ' + selector)
pyppeteer.errors.PageError: No node found for selector: div.login-switch
```

**Comment by wkunzhi** [comment]
Maybe the url HTML has been updated
